Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,20 +1,26 @@
-
-
 #!/usr/bin/env bash
+
 # Transfers a file from our client to a server
-#
-# variables
-path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
-filename=$(basename "$BASH_SOURCE")
-brown='\e[0;33m'
-reset='\033[0m'
+
+# Usage: ./0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
+
+# Variables
 file="$1"
 ip="$2"
 user="$3"
 key="$4"
 
-if [ $# -eq 4 ]; then
-	scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
-else
-	echo -e "Usage: ${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
-fi 
+# Check if all parameters are provided
+if [[ $# -ne 4 ]]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Check if file exists
+if [[ ! -f $file ]]; then
+    echo "Error: File $file not found"
+    exit 1
+fi
+
+# Copy file to server
+scp -o StrictHostKeyChecking=no -i "$key" "$file" "$user"@"$ip":~/ || exit 1
